### ISSUE TITLE
Logi 访问的 JMX 地址与 Kafka 服务配置的 JMX_HOST 不一样

### ISSUE THREAD

**Issue by cobolbaby** [didi/LogiKM#337]
- 自建的 Kafka 提供跨网段支持，编排文件如下:

```
version: '2.3'
services:
  broker1:
    image: registry.inventec/hub/confluentinc/cp-kafka:5.5.2
    container_name: broker1
    networks: 
      - net
    ports:
      - 9092:9092
      - 9093:9093
      - 9094:9094
      - 9095:9095
    volumes:
      - /data/kafka:/kafka
      - /opt/kafka/jmx_exporter:/opt/kafka/jmx_exporter
      - /etc/localtime:/etc/localtime:ro
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LOG_DIRS: /kafka/kafka-logs-broker1
      KAFKA_ZOOKEEPER_CONNECT: 10.0.1.105:2181,10.0.1.106:2181,10.0.1.107:2181
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 30000
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://10.0.1.105:9093,EXTERNAL://10.99.106.108:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LOG_CLEANUP_POLICY: delete,compact
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_RETENTION_BYTES: 21474836480
      # 墓碑消息存留时间
      KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 86400000
      KAFKA_MESSAGE_MAX_BYTES: 31457280
      KAFKA_REPLICA_FETCH_MAX_BYTES: 31457280
      # 不允许自动创建Topic，需要手动创建
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      # 用于端到端测试
      # KAFKA_LOG_MESSAGE_TIMESTAMP_TYPE: LogAppendTime
      KAFKA_HEAP_OPTS: "-Xmx2g -Xms2g"
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_JMX_HOSTNAME: 10.99.106.108
      KAFKA_JMX_PORT: 9095
      KAFKA_OPTS: "-javaagent:/opt/kafka/jmx_exporter/jmx_prometheus_javaagent-0.14.0.jar=9094:/opt/kafka/jmx_exporter/kafka-agent.yml"
      KAFKA_NUM_RECOVERY_THREADS_PER_DATA_DIR: 2
      KAFKA_INTER_BROKER_PROTOCOL_VERSION: "2.5"
      KAFKA_LOG_MESSAGE_FORMAT_VERSION: "2.5"
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
    stop_grace_period: 5m
    logging:
      driver: 'json-file'
      options:
        max-size: 10m
    restart: always
    cpu_count: 2
    mem_limit: 2g

networks:
  net:
    external:
      name: infra
```

- Logi 接入集群的配置:

![2021-06-25 18-12-23屏幕截图](https://user-images.githubusercontent.com/11460848/123409590-eb2e4200-d5e0-11eb-82a2-ef4126b2c3c3.png)

- Logi 的错误日志

Logi 获取的 JMX 地址与服务暴露的不一样，Kafka 配置 JMX 地址的可参考: https://docs.confluent.io/5.5.2/installation/docker/operations/monitoring.html

```
2021-06-25 08:58:47.712 ERROR 6 --- [Call-Thread-2-5] c.x.k.m.c.utils.jmx.JmxConnectorWrap     : JMX connect exception, host:10.0.1.107 port:9095.

java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: 10.0.1.107; nested exception is:
        java.net.ConnectException: Connection timed out (Connection timed out)]
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:369)
        at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
        at com.xiaojukeji.kafka.manager.common.utils.jmx.JmxConnectorWrap.createJmxConnector(JmxConnectorWrap.java:91)
        at com.xiaojukeji.kafka.manager.common.utils.jmx.JmxConnectorWrap.checkJmxConnectionAndInitIfNeed(JmxConnectorWrap.java:60)
        at com.xiaojukeji.kafka.manager.service.service.impl.JmxServiceImpl.getBrokerVersion(JmxServiceImpl.java:526)
        at com.xiaojukeji.kafka.manager.service.cache.PhysicalClusterMetadataManager.getKafkaVersion(PhysicalClusterMetadataManager.java:467)
        at com.xiaojukeji.kafka.manager.service.service.impl.JmxServiceImpl.getBrokerMetrics(JmxServiceImpl.java:53)
        at com.xiaojukeji.kafka.manager.service.service.impl.BrokerServiceImpl.getBrokerMetricsFromJmx(BrokerServiceImpl.java:227)
        at com.xiaojukeji.kafka.manager.service.service.impl.BrokerServiceImpl$1.call(BrokerServiceImpl.java:201)
        at com.xiaojukeji.kafka.manager.service.service.impl.BrokerServiceImpl$1.call(BrokerServiceImpl.java:198)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.naming.ServiceUnavailableException: null
        at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:136)
        at com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:205)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1955)
        at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1922)
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:287)
        ... 15 common frames omitted
Caused by: java.rmi.ConnectException: Connection refused to host: 10.0.1.107; nested exception is:
        java.net.ConnectException: Connection timed out (Connection timed out)
        at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:623)
        at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
        at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
        at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:343)
        at sun.rmi.registry.RegistryImpl_Stub.lookup(RegistryImpl_Stub.java:116)
        at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:132)
        ... 20 common frames omitted
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at java.net.Socket.connect(Socket.java:556)
        at java.net.Socket.<init>(Socket.java:452)
        at java.net.Socket.<init>(Socket.java:229)
        at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)
        at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148)
        at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:617)
        ... 25 common frames omitted
2021-06-25 08:58:47.712 ERROR 6 --- [Call-Thread-2-4] c.x.k.m.c.utils.jmx.JmxConnectorWrap     : JMX connect exception, host:10.0.1.105 port:9095.

java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: 10.0.1.105; nested exception is:
        java.net.ConnectException: Connection timed out (Connection timed out)]
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:369)
        at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
        at com.xiaojukeji.kafka.manager.common.utils.jmx.JmxConnectorWrap.createJmxConnector(JmxConnectorWrap.java:91)
        at com.xiaojukeji.kafka.manager.common.utils.jmx.JmxConnectorWrap.checkJmxConnectionAndInitIfNeed(JmxConnectorWrap.java:60)
        at com.xiaojukeji.kafka.manager.service.service.impl.JmxServiceImpl.getBrokerVersion(JmxServiceImpl.java:526)
        at com.xiaojukeji.kafka.manager.service.cache.PhysicalClusterMetadataManager.getKafkaVersion(PhysicalClusterMetadataManager.java:467)
        at com.xiaojukeji.kafka.manager.service.service.impl.JmxServiceImpl.getBrokerMetrics(JmxServiceImpl.java:53)
        at com.xiaojukeji.kafka.manager.service.service.impl.BrokerServiceImpl.getBrokerMetricsFromJmx(BrokerServiceImpl.java:227)
        at com.xiaojukeji.kafka.manager.service.service.impl.BrokerServiceImpl$1.call(BrokerServiceImpl.java:201)
        at com.xiaojukeji.kafka.manager.service.service.impl.BrokerServiceImpl$1.call(BrokerServiceImpl.java:198)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.naming.ServiceUnavailableException: null
        at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:136)
        at com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:205)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1955)
        at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1922)
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:287)
        ... 15 common frames omitted
Caused by: java.rmi.ConnectException: Connection refused to host: 10.0.1.105; nested exception is:
        java.net.ConnectException: Connection timed out (Connection timed out)
        at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:623)
        at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
        at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
        at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:343)
        at sun.rmi.registry.RegistryImpl_Stub.lookup(RegistryImpl_Stub.java:116)
        at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:132)
        ... 20 common frames omitted
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at java.net.Socket.connect(Socket.java:556)
        at java.net.Socket.<init>(Socket.java:452)
        at java.net.Socket.<init>(Socket.java:229)
        at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)
        at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148)
        at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:617)
        ... 25 common frames omitted
```

**Comment by cobolbaby** [comment]
通过调整 KAFKA_ADVERTISED_LISTENERS 配置的前后顺序避开了该问题

**Comment by cobolbaby** [comment]
ZK broker节点的元信息:

![2021-06-25 18-57-01屏幕截图](https://user-images.githubusercontent.com/11460848/123538413-61f54780-d767-11eb-84cd-b046d36c2351.png)

图中可以看出来 Kafka 暴露端口的两种方式 Internal / External，而Logi-KM解析的时候，使用了前面internal的地址，具体代码在com.xiaojukeji.kafka.manager.service.zookeeper包下面的BrokerStateListener类的processBrokerAdded那个方法，所以造成了其使用了内容广播地址，而非外网广播地址。

**Comment by cobolbaby** [comment]
> 请问一下，存储在zk里面的broker元信息是按照字符串顺序做排序了吗？我是否可以通过调整部署配置的先后顺序将上述问题临时解决？

通过配置 KAFKA_ADVERTISED_LISTENERS 为 `EXTERNAL://10.99.106.108:9092,INTERNAL://10.0.1.105:9093` 的确避开了该问题，但是这种属于取巧的做法，最好 Logi 能够做完善。

**Comment by ZQKC** [comment]
> > 请问一下，存储在zk里面的broker元信息是按照字符串顺序做排序了吗？我是否可以通过调整部署配置的先后顺序将上述问题临时解决？
> 
> 通过配置 KAFKA_ADVERTISED_LISTENERS 为 `EXTERNAL://10.99.106.108:9092,INTERNAL://10.0.1.105:9093` 的确避开了该问题，但是这种属于取巧的做法，最好 Logi 能够做完善。@ZQKC

这块确实是要优化，老哥有没有兴趣贡献一下啊

**Comment by ZQKC** [comment]
近期2.6.0版本我们处理一下该问题～
