### ISSUE TITLE
kafka JMX的hostname设置成0.0.0.0时无法连接

### ISSUE THREAD

**Issue by jeff-zou** [didi/LogiKM#372]
设置成0.0.0.0时是允许所有ip能够连接，但LogiKM无法连接上。错误如下：
2021-09-09 09:41:31.126 ERROR 7 --- [cs-Thread-14-15] c.x.k.m.c.utils.jmx.JmxConnectorWrap     : JMX connect exception, host:****************.com port:9988.

java.rmi.ConnectException: Connection refused to host: 0.0.0.0; nested exception is: 
        java.net.ConnectException: Connection refused (Connection refused)
        at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:623)
        at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
        at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
        at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:132)
        at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:235)
        at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:180)
        at com.sun.proxy.$Proxy129.newClient(Unknown Source)
        at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2430)
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:308)
        at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)

**Comment by ZHAOYINRUI** [comment]
好的，这个问题我们近期关注一下

**Comment by ZQKC** [comment]
应该是JMX配置问题，可以入群(README里有群地址)交流
