### ISSUE TITLE
Zookeeper连接异常恢复之后，"集群管理"列表显示的Topic数仍然为0

### ISSUE THREAD

**Issue by cobolbaby** [didi/LogiKM#375]
com.xiaojukeji.kafka.manager.common.zookeeper.ZkConfigImpl.checkPathExists(ZkConfigImpl.java:140) 抛了 
org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss 异常，之后好像没有异常重试的机制。

**Comment by Huyueeer** [comment]
定位到的具体报错信息：
```java
2021-09-18 13:22:24.959 [Curator-Framework-0] ERROR org.apache.curator.ConnectionState - Connection timed out for connection string (192.168.7.11:2181) and timeout (3000) / elapsed (3000)
org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:197)
	at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:88)
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:116)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:835)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:809)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:64)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:267)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2021-09-18 13:28:52.735 [pool-38-thread-13] ERROR c.x.k.manager.service.utils.KafkaZookeeperUtils - get config data failed, path:/config/topics/xxxx-topic.
com.xiaojukeji.kafka.manager.common.exception.ConfigException: org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
	at com.xiaojukeji.kafka.manager.common.zookeeper.ZkConfigImpl.checkPathExists(ZkConfigImpl.java:144)
	at com.xiaojukeji.kafka.manager.service.utils.KafkaZookeeperUtils.getConfigNodeData(KafkaZookeeperUtils.java:171)
	at com.xiaojukeji.kafka.manager.service.utils.KafkaZookeeperUtils.getConfigData(KafkaZookeeperUtils.java:159)
	at com.xiaojukeji.kafka.manager.service.utils.KafkaZookeeperUtils.getTopicProperties(KafkaZookeeperUtils.java:61)
	at com.xiaojukeji.kafka.manager.task.schedule.metadata.FlushTopicProperties.flush(FlushTopicProperties.java:51)
	at com.xiaojukeji.kafka.manager.task.schedule.metadata.FlushTopicProperties.flush(FlushTopicProperties.java:35)
	at sun.reflect.GeneratedMethodAccessor943.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:197)
	at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:88)
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:116)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getZooKeeper(CuratorFrameworkImpl.java:489)
	at org.apache.curator.framework.imps.ExistsBuilderImpl$3.call(ExistsBuilderImpl.java:226)
	at org.apache.curator.framework.imps.ExistsBuilderImpl$3.call(ExistsBuilderImpl.java:215)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:108)
	at org.apache.curator.framework.imps.ExistsBuilderImpl.pathInForegroundStandard(ExistsBuilderImpl.java:212)
	at org.apache.curator.framework.imps.ExistsBuilderImpl.pathInForeground(ExistsBuilderImpl.java:205)
	at org.apache.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:168)
	at org.apache.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:39)
	at com.xiaojukeji.kafka.manager.common.zookeeper.ZkConfigImpl.checkPathExists(ZkConfigImpl.java:140)
	... 18 common frames omitted
```

**Comment by Huyueeer** [comment]
我研究了一下"Curator"（Zookeeper Client）的实现，是不是在`ExponentialBackoffRetry(1000, 3)`这个重试3次后还没有和Zookeeper构建链接就结束了？此后也不会再有补救措施？
```java
public ZkConfigImpl(String zkAddress, int sessionTimeoutMs, int connectionTimeoutMs, int threadPoolSize) {
        ExponentialBackoffRetry retryPolicy = new ExponentialBackoffRetry(1000, 3);
        CuratorFrameworkFactory.Builder builder = CuratorFrameworkFactory.builder().connectString(zkAddress);
        builder.retryPolicy(retryPolicy);
        builder.sessionTimeoutMs(sessionTimeoutMs).connectionTimeoutMs(connectionTimeoutMs);
        curator = builder.build();
        curator.getConnectionStateListenable().addListener(this);
        curator.start();
        executor = Executors.newFixedThreadPool(threadPoolSize, ThreadUtils.newThreadFactory("PathChildrenCache"));
    }
```

**Comment by ZQKC** [comment]
近期我们看一下这个问题

**Comment by ZQKC** [comment]
> 我研究了一下"Curator"（Zookeeper Client）的实现，是不是在`ExponentialBackoffRetry(1000, 3)`这个重试3次后还没有和Zookeeper构建链接就结束了？此后也不会再有补救措施？
> 
> ```java
> public ZkConfigImpl(String zkAddress, int sessionTimeoutMs, int connectionTimeoutMs, int threadPoolSize) {
>         ExponentialBackoffRetry retryPolicy = new ExponentialBackoffRetry(1000, 3);
>         CuratorFrameworkFactory.Builder builder = CuratorFrameworkFactory.builder().connectString(zkAddress);
>         builder.retryPolicy(retryPolicy);
>         builder.sessionTimeoutMs(sessionTimeoutMs).connectionTimeoutMs(connectionTimeoutMs);
>         curator = builder.build();
>         curator.getConnectionStateListenable().addListener(this);
>         curator.start();
>         executor = Executors.newFixedThreadPool(threadPoolSize, ThreadUtils.newThreadFactory("PathChildrenCache"));
>     }
> ```

是的

**Comment by ZQKC** [comment]
问题长期无更多反馈，后续有类似的，欢迎继续补充，我们再跟进
