### ISSUE TITLE
日志文件中有几种报错；请教下，如何解决？

### ISSUE THREAD

**Issue by meng7even** [didi/LogiKM#464]
目前使用的是LogiKM2.2版本，有几类报错想请教下，如何解决。十分感谢！

## log_error.log
* 一直有这种报错，命令执行查询Offset是正常。
```shell 
org.apache.kafka.common.errors.TimeoutException: Failed to get offsets by times in 15000 ms
2022-02-17 11:22:45.049 [Collect-Metrics-Thread-2-22] ERROR c.x.kafka.manager.service.service.TopicService - get topic endOffsets failed, clusterId:
3 topicName:ABCDE.
```

## metrics/scheduled_tasks.log

1. 第一种报错
```shell
2022-02-17 11:34:25.108 [pool-24-thread-19] ERROR SCHEDULED_TASK_LOGGER - flush topic retention time, get zk config failed, clusterId:8.
```
2. 第二种报错
```shell
2022-02-17 11:34:20.065 [pool-24-thread-14] ERROR SCHEDULED_TASK_LOGGER - collect consumerGroup failed, clusterId:9.
java.lang.RuntimeException: Request METADATA failed on brokers List(192.168.1.8:9092 (id: -1 rack: null), 192.168.1.10:9092 (id: -3 rack: null), 10.
216.94.9:9092 (id: -2 rack: null))
        at kafka.admin.AdminClient.sendAnyNode(AdminClient.scala:66)
        at kafka.admin.AdminClient.findAllBrokers(AdminClient.scala:90)
        at kafka.admin.AdminClient.listAllGroups(AdminClient.scala:98)
        at com.xiaojukeji.kafka.manager.task.schedule.metadata.FlushBKConsumerGroupMetadata.collectAndSaveConsumerGroup(FlushBKConsumerGroupMetadata
.java:78)
        at com.xiaojukeji.kafka.manager.task.schedule.metadata.FlushBKConsumerGroupMetadata.flush(FlushBKConsumerGroupMetadata.java:53)
        at com.xiaojukeji.kafka.manager.task.schedule.metadata.FlushBKConsumerGroupMetadata.schedule(FlushBKConsumerGroupMetadata.java:41)
        at sun.reflect.GeneratedMethodAccessor209.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

3. 第三种报错
```shell
2022-02-17 11:33:35.009 [Collect-Metrics-Thread-2-211] ERROR SCHEDULED_TASK_LOGGER - collect topicName and consumerGroup failed, clusterId:3 consume
rGroup:ABCDE.
com.xiaojukeji.kafka.manager.common.exception.ConfigException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /c
onsumers/ABCDE/offsets
        at com.xiaojukeji.kafka.manager.common.zookeeper.ZkConfigImpl.getChildren(ZkConfigImpl.java:362)
        at com.xiaojukeji.kafka.manager.task.schedule.metadata.FlushZKConsumerGroupMetadata$1.call(FlushZKConsumerGroupMetadata.java:90)
        at com.xiaojukeji.kafka.manager.task.schedule.metadata.FlushZKConsumerGroupMetadata$1.call(FlushZKConsumerGroupMetadata.java:86)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /consumers/ABCDE/offsets
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:111)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
        at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1590)
        at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:214)
        at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:203)
        at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:108)
        at org.apache.curator.framework.imps.GetChildrenBuilderImpl.pathInForeground(GetChildrenBuilderImpl.java:200)
        at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:191)
        at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:38)
        at com.xiaojukeji.kafka.manager.common.zookeeper.ZkConfigImpl.getChildren(ZkConfigImpl.java:360)
        ... 8 common frames omitted
```

**Comment by ZQKC** [comment]
1、Failed to get offsets by times in 15000 ms：
检查接入集群是否正常，集群的版本要求0.10.2及以上，以上如果都正常，再检查Topic是否正常。

2、flush topic retention time, get zk config failed：
检查接入的集群的ZK是否正常；

3、collect consumerGroup failed, clusterId:9.
检查集群的__consumer_offsets这个Topic是否正常，以及集群是否正常。

4、KeeperException$NoNodeException
使用了ZK的消费组，在ZK上的信息是否完整。

通用检查部分，集群的版本要求0.10.2及以上，KM和集群之间的网络等都正常，出问题的相关Topic或者Group是否都正常。

**Comment by ZQKC** [comment]
无更多反馈，关闭该Issue

**Comment by ZQKC** [comment]
> 感谢答复，我用的kafka版本是0.8版本的。我先升级集群，再看下是否能解决！

嗯，好的

**Comment by 1299618103** [comment]
我也遇到了这个问题，日志一直在报错：
org.apache.kafka.common.errors.TimeoutException: Failed to get offsets by times in 15000 msERROR 1 --- [cs-Thread-2-170] c.x.k.m.service.service.TopicService     : get topic endOffsets failed, clusterId:3 topicName: xxx
kafka 版本是：1.1.1-cp1
大量topic 都在报这个错误，集群是还在正常使用的

**Comment by ZQKC** [comment]
> 我也遇到了这个问题，日志一直在报错： org.apache.kafka.common.errors.TimeoutException: Failed to get offsets by times in 15000 msERROR 1 --- [cs-Thread-2-170] c.x.k.m.service.service.TopicService : get topic endOffsets failed, clusterId:3 topicName: xxx kafka 版本是：1.1.1-cp1 kafka manage 使用的是k8s镜像：kafka-manager:v2.1.2 大量topic 都在报这个错误，集群是还在正常使用的

在KS所在的机器上，用2.x版本的kafka的脚本，查询一下报错的Topic是否可以正常查询offset信息。如果可以，那么试着调大一下ks的线程池，如果不可以，辛苦排查一下kafka集群，或者网络是否有问题，
