### ISSUE TITLE
Logi-KM配置JMX后，链接报错

### ISSUE THREAD

**Issue by meng7even** [didi/LogiKM#478]
# Logi-KM配置JMX后，log_error.log有报错。

通过Jconsole测试也可以链上的。并且集群目前正常。配置信息如下：

### kafka-server-start.sh
```
if [ "x$KAFKA_HEAP_OPTS" = "x" ]; then
    export KAFKA_HEAP_OPTS="-Xmx1G -Xms1G"
    export JMX_PORT=9988
fi
```

### kafka-run-class.sh
```# JMX settings
if [ -z "$KAFKA_JMX_OPTS" ]; then
  KAFKA_JMX_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false  -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=192.168.3.10"
fi
# JMX port to use
if [  $JMX_PORT ]; then
  KAFKA_JMX_OPTS="$KAFKA_JMX_OPTS -Dcom.sun.management.jmxremote.port=$JMX_PORT -Dcom.sun.management.jmxremote.rmi.port=$JMX_PORT"
fi
```

## 报错如下：

```2022-03-11 18:04:21.034 [CustomScheduled-collectAndPublishBrokerMetrics-12-2] ERROR c.x.k.manager.common.utils.jmx.JmxConnectorWrap - connect JMX failed, physicalClusterId:9 brokerId:2 host:192.168.3.10 port:9988.
java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is: 
        javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake]
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:369)
        at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
        at com.xiaojukeji.kafka.manager.common.utils.jmx.JmxConnectorWrap.createJmxConnector(JmxConnectorWrap.java:137)
        at com.xiaojukeji.kafka.manager.common.utils.jmx.JmxConnectorWrap.safeCreateJmxConnector(JmxConnectorWrap.java:105)
        at com.xiaojukeji.kafka.manager.common.utils.jmx.JmxConnectorWrap.checkJmxConnectionAndInitIfNeed(JmxConnectorWrap.java:74)
        at com.xiaojukeji.kafka.manager.service.service.impl.JmxServiceImpl.getBrokerVersion(JmxServiceImpl.java:529)
        at com.xiaojukeji.kafka.manager.service.cache.PhysicalClusterMetadataManager.getKafkaVersion(PhysicalClusterMetadataManager.java:493)
        at com.xiaojukeji.kafka.manager.service.service.impl.JmxServiceImpl.getBrokerMetrics(JmxServiceImpl.java:56)
        at com.xiaojukeji.kafka.manager.task.dispatch.metrics.collect.CollectAndPublishBrokerMetrics.getBrokerMetrics(CollectAndPublishBrokerMetrics.java:69)
        at com.xiaojukeji.kafka.manager.task.dispatch.metrics.collect.CollectAndPublishBrokerMetrics.processTask(CollectAndPublishBrokerMetrics.java:57)
        at com.xiaojukeji.kafka.manager.task.dispatch.metrics.collect.CollectAndPublishBrokerMetrics.processTask(CollectAndPublishBrokerMetrics.java:29)
        at com.xiaojukeji.kafka.manager.task.component.BaseBizTask.run(BaseBizTask.java:28)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: javax.naming.CommunicationException: null
        at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:136)
        at com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:205)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1955)
        at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1922)
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:287)
        ... 16 common frames omitted
Caused by: java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is: 
        javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
        at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:307)
        at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
        at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:342)
        at sun.rmi.registry.RegistryImpl_Stub.lookup(RegistryImpl_Stub.java:116)
        at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:132)
        ... 21 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
        at sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1506)
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1323)
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1228)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412)
        at sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:832)
        at sun.security.ssl.SSLSocketImpl.access$200(SSLSocketImpl.java:76)
        at sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1133)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at java.io.DataOutputStream.flush(DataOutputStream.java:123)
        at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:229)
        ... 25 common frames omitted
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:480)
        at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:469)
        at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:159)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1315)
        ... 34 common frames omitted
```

## Logi-KM的集群配置里的JMX认证：

```
{
    "maxConn": 10,
    "username": "admin",
    "password": "111111",
    "openSSL": false,
}
```

**Comment by meng7even** [comment]
Kafka集群版本为2.5.0，Logi-KM版本为2.6

**Comment by ZQKC** [comment]
> Kafka集群版本为2.5.0，Logi-KM版本为2.6

如果未开启，则配置：
{
    "maxConn": 10
}

如果开启，则配置：
{
    "maxConn": 10,
    "username": "admin",
    "password": "111111",
    "openSSL": true,
}

试一下看看，看错误是ssl的时候有问题。

**Comment by meng7even** [comment]
> > Kafka集群版本为2.5.0，Logi-KM版本为2.6
> 
> 如果未开启，则配置： { "maxConn": 10 }
> 
> 如果开启，则配置： { "maxConn": 10, "username": "admin", "password": "111111", "openSSL": true, }
> 
> 试一下看看，看错误是ssl的时候有问题。

感谢！已经解决了！按照配置，重启后，生效了。
