### ISSUE TITLE
编译时候报错，可能跟前端的配置相关？不太懂前端，麻烦帮忙看一下

### ISSUE THREAD

**Issue by jimiao1125** [didi/LogiKM#507]
2022-07-28 18:19:41.128  INFO 24900 --- [           main] o.a.coyote.http11.Http11NioProtocol      : Initializing ProtocolHandler ["http-nio-8080"]
2022-07-28 18:19:41.144  INFO 24900 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-07-28 18:19:41.144  INFO 24900 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/8.5.72]
2022-07-28 18:19:41.253  INFO 24900 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-07-28 18:19:41.253  INFO 24900 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 2073 ms
2022-07-28 18:19:41.898  INFO 24900 --- [           main] x.k.m.s.c.PhysicalClusterMetadataManager : cluster metadata initialization start.
2022-07-28 18:19:41.914  INFO 24900 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2022-07-28 18:19:42.011  INFO 24900 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2022-07-28 18:19:42.027  INFO 24900 --- [           main] x.k.m.s.c.PhysicalClusterMetadataManager : cluster metadata initialization finished.
2022-07-28 18:19:43.088  INFO 24900 --- [           main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [public org.springframework.http.ResponseEntity<springfox.documentation.spring.web.json.Json> springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(java.lang.String,javax.servlet.http.HttpServletRequest)]
2022-07-28 18:19:43.312  WARN 24900 --- [           main] ion$DefaultTemplateResolverConfiguration : Cannot find template location: classpath:/templates/ (please add some templates or check your Thymeleaf configuration)
2022-07-28 18:19:43.396  INFO 24900 --- [           main] d.s.w.p.DocumentationPluginsBootstrapper : Context refreshed
2022-07-28 18:19:43.443  INFO 24900 --- [           main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
2022-07-28 18:19:43.526  INFO 24900 --- [           main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
2022-07-28 18:19:43.912  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getAppIdQuotaUsingGET_1
2022-07-28 18:19:43.912  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getAppIdQuotaUsingGET_2
2022-07-28 18:19:44.112  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getTopicMetricsUsingGET_1
2022-07-28 18:19:44.127  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getTopicRequestMetricsUsingGET_1
2022-07-28 18:19:44.200  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getExpiredTopicsUsingGET_1
2022-07-28 18:19:44.211  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getClusterModesEnumUsingGET_1
2022-07-28 18:19:44.216  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: preferredReplicaElectUsingPOST_1
2022-07-28 18:19:44.220  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: preferredReplicaElectStatusUsingGET_1
2022-07-28 18:19:44.230  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: executeReassignTopicTaskUsingPUT_1
2022-07-28 18:19:44.233  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: createCommonTopicUsingPOST_1
2022-07-28 18:19:44.233  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: deleteTopicsUsingDELETE_1
2022-07-28 18:19:44.248  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: expandTopicsUsingPUT_1
2022-07-28 18:19:44.248  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: modifyTopicUsingPUT_1
2022-07-28 18:19:44.248  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: modifyTopicUsingPUT_2
2022-07-28 18:19:44.248  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getAppsUsingGET_1
2022-07-28 18:19:44.264  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getBillStaffDetailUsingGET_1
2022-07-28 18:19:44.264  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getBillStaffSummaryUsingGET_1
2022-07-28 18:19:44.264  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getBillStaffSummaryUsingGET_2
2022-07-28 18:19:44.295  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getBrokerOverviewUsingGET_1
2022-07-28 18:19:44.295  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getClusterBasicInfoUsingGET_1
2022-07-28 18:19:44.311  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getClusterMetricsHistoryUsingGET_1
2022-07-28 18:19:44.311  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getClusterRealTimeMetricsUsingGET_1
2022-07-28 18:19:44.311  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getThrottlesUsingGET_1
2022-07-28 18:19:44.311  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getTopicMetadatasUsingGET_1
2022-07-28 18:19:44.311  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getTopicOverviewUsingGET_1
2022-07-28 18:19:44.342  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getKafkaFilesUsingGET_1
2022-07-28 18:19:44.358  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: deleteByIdUsingDELETE_1
2022-07-28 18:19:44.373  WARN 24900 --- [           main] s.d.s.w.r.p.ParameterDataTypeReader      : Trying to infer dataType java.util.List<com.xiaojukeji.kafka.manager.common.entity.dto.ClusterTopicDTO>
2022-07-28 18:19:44.373  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: createNewUsingPOST_1
2022-07-28 18:19:44.373  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: deleteByIdUsingDELETE_2
2022-07-28 18:19:44.389  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getTopicBasicUsingGET_1
2022-07-28 18:19:44.404  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getBrokerOverviewUsingGET_2
2022-07-28 18:19:44.404  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getConsumeDetailUsingGET_1
2022-07-28 18:19:44.420  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getConsumeDetailUsingGET_2
2022-07-28 18:19:44.436  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getTopicMetricsUsingGET_2
2022-07-28 18:19:44.436  INFO 24900 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getTopicRequestMetricsUsingGET_2
2022-07-28 18:19:44.467  INFO 24900 --- [           main] o.a.coyote.http11.Http11NioProtocol      : Starting ProtocolHandler ["http-nio-8080"]
2022-07-28 18:19:44.467  INFO 24900 --- [           main] o.a.tomcat.util.net.NioSelectorPool      : Using a shared selector for servlet write/read
2022-07-28 18:19:44.483  INFO 24900 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2022-07-28 18:19:44.498  INFO 24900 --- [           main] c.x.kafka.manager.web.MainApplication    : Started MainApplication in 5.871 seconds (JVM running for 6.289)
2022-07-28 18:19:44.498  INFO 24900 --- [           main] c.x.kafka.manager.web.MainApplication    : MainApplication started
2022-07-28 18:19:48.090  INFO 24900 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-07-28 18:19:48.090  INFO 24900 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2022-07-28 18:19:48.100  INFO 24900 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 10 ms
2022-07-28 18:19:48.249 ERROR 24900 --- [nio-8080-exec-1] org.thymeleaf.TemplateEngine             : [THYMELEAF][http-nio-8080-exec-1] Exception processing template "index": Error resolving template [index], template might not exist or might not be accessible by any of the configured Template Resolvers

org.thymeleaf.exceptions.TemplateInputException: Error resolving template [index], template might not exist or might not be accessible by any of the configured Template Resolvers
	at org.thymeleaf.engine.TemplateManager.resolveTemplate(TemplateManager.java:869)
	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:607)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1098)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1072)
	at org.thymeleaf.spring5.view.ThymeleafView.renderFragment(ThymeleafView.java:362)
	at org.thymeleaf.spring5.view.ThymeleafView.render(ThymeleafView.java:189)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1372)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1118)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1057)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:196)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:364)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:624)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1650)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)

2022-07-28 18:19:48.251 ERROR 24900 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateInputException: Error resolving template [index], template might not exist or might not be accessible by any of the configured Template Resolvers] with root cause

org.thymeleaf.exceptions.TemplateInputException: Error resolving template [index], template might not exist or might not be accessible by any of the configured Template Resolvers
	at org.thymeleaf.engine.TemplateManager.resolveTemplate(TemplateManager.java:869)
	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:607)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1098)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1072)
	at org.thymeleaf.spring5.view.ThymeleafView.renderFragment(ThymeleafView.java:362)
	at org.thymeleaf.spring5.view.ThymeleafView.render(ThymeleafView.java:189)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1372)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1118)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1057)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:196)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:364)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:624)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1650)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)

**Comment by jimiao1125** [comment]
2022-07-28 18:19:48.249 ERROR 24900 --- [nio-8080-exec-1] org.thymeleaf.TemplateEngine : [THYMELEAF][http-nio-8080-exec-1] Exception processing template "index": Error resolving template [index], template might not exist or might not be accessible by any of the configured Template Resolvers

org.thymeleaf.exceptions.TemplateInputException: Error resolving template [index], template might not exist or might not be accessible by any of the configured Template Resolvers

**Comment by jimiao1125** [comment]
版本 release/v2.6.0

**Comment by jimiao1125** [comment]
在idea中启动，按照
“如果想参与开发或者想在IDE中启动的话 先执行 mvn -Dmaven.test.skip=true clean install -U

然后这个时候可以选择去 [pom.xml](file:///D:/software/LogiKM-2.6.0/LogiKM-2.6.0/pom.xml) 中将kafka-manager-console模块注释掉; 注释是因为每次install的时候都会把前端文件kafka-manager-console重新打包进kafka-manager-web

完事之后,只需要直接用IDE启动运行kafka-manager-web模块中的 com.xiaojukeji.kafka.manager.web.MainApplication main方法就行了
”
执行

**Comment by ZQKC** [comment]
1、检查一下 kafka-manager-web/src/main/resources/templates 这个目录下是否有前端静态资源文件；
2、如果没有，则不能注释kafka-manager-console模块，然后重新执行mvn -Dmaven.test.skip=true clean install -U，使其产出相关前端文件；
3、如果有了，则ID E直接启动就可以了；
